name: dedepos
description: dede pos project.

publish_to: "none"

version: 1.3.6+34

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  desktop_window: ^0.4.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3  
  cupertino_icons: ^1.0.5
  dart_ping_ios: ^3.0.0
  decorated_icon: ^1.2.1
  device_info_plus: ^9.0.3
  dio: ^5.1.1
  equatable: ^2.0.5
  esc_pos_printer: ^4.1.0
  flutter_barcode_listener: ^0.1.3
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  get_storage: ^2.1.1
  html: ^0.15.2
  http: ^1.1.0
  image: ^3.3.0
  just_audio: ^0.9.32
  loader_overlay: ^2.2.0
  material_tag_editor: ^0.1.2
  page_transition: ^2.0.9
  path_provider: ^2.0.14
  pattern_formatter: ^3.0.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.1.0
  split_view: ^3.2.1
  visibility_detector: ^0.4.0+2
  countdown_progress_indicator: ^0.1.2
  decimal: ^2.3.2
  buddhist_datetime_dateformat_sns: ^1.0.7
  get_localization: ^3.0.0
  fullscreen: ^1.0.3
  web_socket_channel: ^2.4.0
  flutter_usb_printer: ^0.1.0+1
  objectbox: ^2.0.0
  json_annotation: ^4.8.1
  objectbox_generator: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  archive: ^3.3.2
  get: ^4.6.5
  loading_animation_widget: ^1.2.0+4
  qr_code_scanner: ^1.0.1
  charset_converter: ^2.1.1
  sunmi_printer_plus: ^2.1.1
  network_info_plus: ^3.0.3
  network_tools: ^3.0.0+3
  esc_pos_utils: ^1.1.0
  flutter_flavorizr: ^2.1.5
  presentation_displays: ^0.2.3
  video_player: ^2.6.1
  text_to_speech: ^0.2.3
  geolocator: ^10.0.0
  audio_session: ^0.1.13
  win32: ^5.0.6
  ffi: ^2.0.1
  uuid: ^3.0.7
  bloc: ^8.1.1
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  auto_route: ^7.2.0
  dartz: ^0.10.1
  mocktail: ^1.0.0
  collection: ^1.17.1
  logger: ^2.0.1
  qr_flutter: ^4.1.0
  connectivity_plus: ^4.0.2
  sunmi_ext_printer: ^0.0.1
  print_bluetooth_thermal: ^1.0.9
  flutter_pos_printer_platform: ^1.1.0
  gsheets: ^0.5.0
  permission_handler: ^10.3.0
  slider_captcha: ^1.0.0
  animated_icon: ^0.0.5
  url_launcher: ^6.1.12
  top_snackbar_flutter: ^3.1.0
  network_to_file_image: ^4.0.1
  camera: ^0.10.5+2
  drop_shadow: ^0.1.0
  simple_shadow: ^0.3.1
  promptpay:
    path: packages/promptpay
  lugentpayment:
    path: packages/lugentpay
  flutter_rounded_date_picker:
    path: packages/flutter_rounded_date_picker

dev_dependencies:
  flutter_driver:
    sdk: flutter
  analyzer: ^5.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^7.1.1
  msix: ^3.7.0
  flutter_flavorizr: ^2.1.5

dependency_overrides:
  intl: ^0.17.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
    - assets/images/
    - assets/images/qrpay/
    - assets/icons/
    - assets/flags/
    - assets/fonts/

  fonts:
    - family: prompt
      fonts:
        - asset: assets/fonts/prompt/Prompt-Regular.ttf
        - asset: assets/fonts/prompt/Prompt-Bold.ttf
        - asset: assets/fonts/prompt/Prompt-SemiBold.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
    windows:
    macos:

  flavors:
    dev:
      app:
        name: "DEDE POS DEV"
        icon: "assets/app_logo.png"
      android:
        applicationId: "com.smlsoft.dedepos"
      ios:
        bundleId: "com.smlsoft.dedepos"
      windows:
        packageId: "com.smlsoft.dedepos"
      macos:
        bundleId: "com.smlsoft.dedepos"

    dedepos:
      app:
        name: "DEDE POS"
        icon: "assets/icons/dede-pos-icon.png"
      android:
        applicationId: "com.smlsoft.dedepos"
      ios:
        bundleId: "com.smlsoft.dedepos"
      windows:
        packageId: "com.smlsoft.dedepos"
        # customConfig:
        #   msix_config:
        #     display_name: DEDEPOS
        #     publisher_display_name: SMLSoft
        #     publisher: CN=55D8FA38-A305-463E-8BA0-21DE7B40BA27
        #     identity_name: 	SMLSoft.DEDEPOS
        #     msix_version: 1.0.0.0
        #     logo_path: .\assets\dede-pos-icon.png
        #     capabilities: internetClient, location, microphone, webcam
        #     # certificate_path: D:\CODE2121\flutter\dedepos_testflight_deploy\key\CERTIFICATE.pfx
        #     # certificate_password: sml19682511
      macos:
        bundleId: "com.smlsoft.dedepos"

    smlsuperpos:
      app:
        name: "SML Super POS"
        icon: "assets/app_logo.png"
      android:
        applicationId: "com.smlsoft.smlsuperpos"
      ios:
        bundleId: "com.smlsoft.smlsuperpos"
      windows:
        packageId: "com.smlsoft.smlsuperpos"
      macos:
        bundleId: "com.smlsoft.smlsuperpos"

    smlmobilesales:
      app:
        name: "SML Mobile Sales"
        icon: "assets/app_logo.png"
      android:
        applicationId: "com.smlsoft.smlmobilesales"
      ios:
        bundleId: "com.smlsoft.smlmobilesales"
      windows:
        packageId: "com.smlsoft.smlmobilesales"
      macos:
        bundleId: "com.smlsoft.smlmobilesales"

    vfpos:
      app:
        name: "Village Fund POS"
        icon: "assets/vf-pos-logo.png"
      android:
        applicationId: "org.villagefundth.vfpos"
        # signingConfig: // ใส่ชื่อ signingConfig ที่เราสร้างไว้ในไฟล์ android/app/build.gradle
      ios:
        bundleId: "org.villagefundth.vfpos"
      windows:
        packageId: "org.villagefundth.vfpos"
        # customConfig:
        #   msix_config:
        #     display_name: VFPOS
        #     publisher_display_name: SMLSoft
        #     identity_name: com.smlsoft.vfpos
        #     msix_version: 1.0.0.0
        #     logo_path: .\assets\vf-pos-icon.png
        #     capabilities: internetClient, location, microphone, webcam
        #     certificate_path: D:\CODE2121\flutter\dedepos_testflight_deploy\key\CERTIFICATE.pfx
        #     certificate_password: sml19682511
      macos:
        bundleId: "org.villagefundth.vfpos"
msix_config:
  # # DEDE POS Store Config
  # display_name: DEDEPOS
  # publisher_display_name: SMLSoft
  # publisher: CN=55D8FA38-A305-463E-8BA0-21DE7B40BA27
  # identity_name: 	SMLSoft.DEDEPOS
  # msix_version: 1.0.0.0
  # logo_path: .\assets\dede-pos-icon.png
  # capabilities: internetClient, location, microphone, webcam
  # store: true

  # DEDE POS Dev Install Config
  display_name: DEDEPOS
  publisher_display_name: SMLSoft
  publisher: smlsoft
  identity_name: com.smlsoft.vfpos
  # language: en-us
  # capabilities: internetClient, location, microphone, webcam
  # certificate_path: C:\source\flutter-test-key\CERTIFICATE.pfx
  # certificate_password: sml19682511
