// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8wwIwLSsMEefD-cD0FAgBRgIr4SLISk',
    appId: '1:183871505957:web:97c3142269fffda907a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    authDomain: 'dedepos.firebaseapp.com',
    storageBucket: 'dedepos.appspot.com',
    measurementId: 'G-GPRHK8FH01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHfJ-wnQfzD4BSQeXggora43ygd5sRwcU',
    appId: '1:183871505957:android:369ec195ada87f3f07a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ931rkxwdcUScQBvgGK8aAhBYsM6-kbY',
    appId: '1:183871505957:ios:731413d8fbd52a2907a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
    androidClientId: '183871505957-f4afcfn804071c18ujqjlgb1gth2d7kv.apps.googleusercontent.com',
    iosClientId: '183871505957-93bglibtnlmgnb7ftp9i8dli08dn27nm.apps.googleusercontent.com',
    iosBundleId: 'com.smlsoft.dedepos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ931rkxwdcUScQBvgGK8aAhBYsM6-kbY',
    appId: '1:183871505957:ios:731413d8fbd52a2907a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
    androidClientId: '183871505957-f4afcfn804071c18ujqjlgb1gth2d7kv.apps.googleusercontent.com',
    iosClientId: '183871505957-93bglibtnlmgnb7ftp9i8dli08dn27nm.apps.googleusercontent.com',
    iosBundleId: 'com.smlsoft.dedepos',
  );
}
